packages:
  - 'packages/*'

catalog:
  react: ^18.3.1
  react-dom: ^18.3.1
  vite: ^5.4.9
  vite-plugin-dts: ~3.8.1
  vitest: ^1.3.1
  typescript: ~5.6.2
  typescript-eslint: ^8.10.0
  eslint: ^9.13.0
  eslint-plugin-react-hooks: ^5.0.0
  eslint-plugin-react-refresh: ^0.4.13
  globals: ^15.11.0
  '@eslint/js': ^9.13.0
  '@types/node': ^18.18.0
  '@types/react': ^18.3.11
  '@types/react-dom': ^18.3.1
  '@vitejs/plugin-react': ^4.3.3
