name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  publish:
    permissions:
      contents: write #  to be able to publish a GitHub release
      issues: write #  to be able to comment on released issues
      pull-requests: write #  to be able to comment on released pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'

      - name: Generate .npmrc
        run: |
          pnpm config set @ccreusat:registry https://registry.npmjs.org
          pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          pnpm config set auto-install-peers true
          pnpm config set strict-peer-dependencies false

      - run: pnpm install --no-frozen-lockfile
        name: Install & Build

      - uses: nrwl/nx-set-shas@v4

      - name: Affected build
        run: pnpm exec nx affected -t build

      - name: Version & Publish
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          echo "Your current branch is ${{ github.ref_name }}"

          if [ ${{ github.ref_name }} = "main" ]; then
            echo "This is the main branch."
            pnpm nx release --first-release --skip-publish
            pnpm nx release publish --output-style=stream
          else
            echo "This is not the main branch."
            pnpm nx release --skip-publish
            pnpm nx release publish --tag ${{ github.ref_name }} --output-style=stream
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
